remote_theme: ddc-java/ddc-day
title: Style Guide
description: Coding conventions for the Deep Dive Coding Java + Android Bootcamp
author:
  name: Nick Bennett
  email: nick@nickbenn.com
heading_navigator: 
  enabled: true
  to: 2

