remote_theme: ddc-java/ddc-day
title: DDC Style Guide
description: Coding conventions for the Deep Dive Coding Java + Android Bootcamp
author:
  name: Nick Bennett
  email: nick@nickbenn.com
repository_link: 
  enabled: true
